# Generated by Django 6.0.6 on 2026-06-23 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ultimate',
            table='wscdatabase_Ultimate',
        ),
        migrations.AlterModelTable(
            name='woodspecies',
            table='wscdatabase_WoodSpecies',
        ),
        migrations.AlterModelTable(
            name='worktype',
            table='wscdatabase_WorkType',
        ),
    ]
