# Generated by Django 6.0.6 on 2026-06-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wscdatabase', '0002_alter_ultimate_table_alter_woodspecies_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cabacc',
            table='wscdatabase_CabAcc',
        ),
        migrations.AlterModelTable(
            name='comp',
            table='wscdatabase_Comp',
        ),
    ]
